from __future__ import annotations

import json
import re
from collections import defaultdict, deque
from pathlib import Path

ROOT = Path(r"E:/BOT")


def write(rel: str, text: str) -> None:
    path = ROOT / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def spec(title, purpose, requirements, contracts, invariants, states, tests, prs, refs):
    return f"""# {title}

**Status:** `PROPOSED` — planning contract only; no control described here exists until its named implementation, test, audit, and activation evidence are independently PASS.

## Purpose and boundary

{purpose}

## Normative requirements

{requirements}

## Component contracts

{contracts}

## Invariants and deny conditions

{invariants}

## State and failure semantics

{states}

## Future verification

{tests}

## Queue ownership

Implementation is decomposed in `{prs}`. Every dependent card is blocked by unresolved Q-gates, missing provider evidence, or a non-PASS predecessor.

## Detailed reference and provenance

Planning detail is cross-checked against `{refs}`. External facts remain subject to `.planning/master/SOURCES_EVIDENCE.md`; source reachability is never capability, contractual, regulatory, or production proof.
"""

specs = {
"docs/specifications/PRODUCT_SPEC.md": spec("Product Specification", "Defines a capital-preservation-control platform, not a promise of profit or loss protection. User modes are MANUAL, AI_ADVISORY, AI_PROPOSE, and AI_AUTO_WITH_LIMITS; only the first three may be planned before evidence gates admit the last.", "- Account, strong authentication, balances, activity, deposits and future withdrawals are tenant-scoped views of authoritative domain records.\n- Feature flags default OFF for `ARBITRAGE`, `DEX`, `LP`, `AUTO_LP`, `WITHDRAW_PIX`, `WITHDRAW_CRYPTO`, `METAMASK`, `AI_AUTOPILOT`, and `MAINNET`.\n- MVP-A is identity + ledger + payment sandbox specification + market-data paper view + risk dashboard; later MVPs remain gated.", "ProductMode, FeatureFlag, UserDisclosureVersion, PortfolioView, ActivityFeed, ReadModelProjection.", "No UI or mode may manufacture availability, execute an external action, or hide a denied/risk/reconciliation status. Customer language MUST NOT imply guaranteed capital protection, suitability, licensing, custody, or return.", "Mode transition: MANUAL→AI_ADVISORY→AI_PROPOSE→AI_AUTO_WITH_LIMITS is monotonic only after product, legal, risk, security and mainnet gates; any gate regression returns the affected capability to DENIED.", "UX contract tests for feature-flag denial, tenant visibility, disclosure rendering and capability regression; E2E tests later prove an off flag has no API side effect.", "PR-001..PR-010", "docs/reference-formalization/specifications/00-charter-scope-and-terminology.md"),
"docs/architecture/SYSTEM_ARCHITECTURE.md": spec("System Architecture", "Defines a modular monolith around a language-neutral safety contract. The container shape may later use Next.js/TypeScript UI and a Rust critical kernel only after ADR-001 evidence gate; the architecture does not assume language capability as proof.", "- Modules own persistence and expose versioned commands/events; cross-module writes are forbidden except a capability-scoped transaction kernel.\n- PostgreSQL is the initial authoritative relational store; local inbox/outbox is the only delivery mechanism until workload evidence justifies a broker.\n- UI/API, identity, ledger, payment, market, strategy, risk, execution, reconciliation and audit are modules, not premature services.\n- SSE is preferred for initial server→browser activity; WebSocket needs a named bidirectional use case.", "CommandEnvelope, EventEnvelope, TransactionKernel, ModuleContract, ReadProjection, CapabilityGrant.", "No distributed transaction claim. No module may bypass ledger, policy, transaction guard, audit or tenant context. Unknown action/environment/capability contracts default deny.", "Command flow: API→module validation→policy/risk→simulation→guard→local transaction+outbox→privileged adapter (when authorized)→evidence→reconciliation→projection.", "Architecture dependency test, forbidden shared-write test, transaction-kernel integration test, outbox/inbox replay test and no-privileged-bypass test.", "PR-001..PR-018", "docs/reference-formalization/specifications/01-domain-data-and-module-boundaries.md; docs/reference-formalization/specifications/02-financial-authority-and-policy-kernel.md"),
"docs/architecture/DOMAIN_MODEL.md": spec("Domain Model", "Defines aggregates and authority ownership for Identity, Tenant, Ledger, Payment, Withdrawal, Wallet, Capability Claim, Market Snapshot, Strategy Proposal, Risk Decision, Execution Intent, Position, Reconciliation Case and Audit Event.", "- Aggregates publish immutable versioned events and have one command owner.\n- Financial authority is separated from external observation and user-facing projections.\n- Strategy/AI objects are non-authoritative recommendations; ExecutionIntent is created only by deterministic authorization.", "TenantId, AssetId, Money, Quantity, CorrelationId, CausationId, IdempotencyScope, PolicyVersion, EvidenceRef, CapabilityGrantRef.", "All IDs carry tenant/environment context where relevant; Money uses integer atoms plus asset scale, never IEEE float. A projection cannot be command authority.", "Proposal, payment, withdrawal, execution, order, LP and reconciliation lifecycles are defined in `.planning/contracts/STATE_MACHINES.md`.", "Generated model/state-machine tests, aggregate command idempotency tests, ownership tests and domain-event compatibility tests.", "PR-011..PR-026", "docs/reference-formalization/contracts/02-state-machines-and-invariants.md"),
"docs/architecture/DATA_MODEL.md": spec("Data Model", "Defines relational schema boundaries and migrations for immutable financial records, tenant isolation and PII separation. It is a logical design only; migrations are future work.", "- Tables include users, sessions, auth_methods, wallets, wallet_addresses, exchange_accounts, deposits, withdrawals, ledger_accounts, ledger_entries, ledger_postings, assets, chains, protocols, pools, positions, lp_positions, orders, trades, strategies, strategy_runs, strategy_proposals, risk_decisions, transactions, blockchain_transactions, market_snapshots, audit_events and api_credentials_metadata.\n- Secrets are references to a secret manager, never values.\n- PII, financial records, credentials metadata and trading data have separate classification/retention rules.", "TenantScopedRow, ImmutableJournalEntry, Posting, ProviderEvidence, OutboxMessage, InboxRecord, ReconciliationCase.", "Row-level policy and application authorization must agree; every financial mutation has correlation/idempotency keys; posted journal rows are immutable; corrections are compensating entries.", "Migrations are expand→backfill→contract; destructive migration needs restore rehearsal and accounting sign-off.", "Migration replay, RLS negative tests, unique/idempotency constraints, schema contract tests and retention/deletion policy tests.", "PR-019..PR-034", "docs/reference-formalization/specifications/01-domain-data-and-module-boundaries.md; docs/reference-formalization/specifications/03-ledger-and-accounting.md"),
"docs/security/TRUST_BOUNDARIES.md": spec("Trust Boundaries", "Defines identity, browser, API, tenant, provider, signer, database, observability and operator boundaries.", "- Browser/MetaMask, Mercado Pago, exchanges, RPCs, DEXes and AI providers are untrusted external systems.\n- Privileged adapters use attenuated capabilities bound to service identity, tenant, operation/resource, audience, environment, expiry, rotation and revocation.\n- LLM input/output, webhook payloads, market data, calldata candidates and provider status are untrusted input.", "CapabilityGrant, ServiceIdentity, EvidenceClaim, AdapterResponse, HumanApproval, EnvironmentAttestation.", "No ambient provider credential in tenant-facing code. No raw private key in SQL, environment variables, logs or LLM context. Denials use generic response plus pseudonymous audit evidence.", "Boundary crossings validate schema, signature/authentication where supported, scope, freshness, allowlist, replay, rate limit and policy disposition.", "Threat-driven negative tests: cross-tenant substitution, stale capability, audience mismatch, impersonated provider, replay, malformed payload and log redaction.", "PR-027..PR-040", "docs/reference-formalization/specifications/10-auth-trust-threat-and-security.md"),
"docs/security/THREAT_MODEL.md": spec("Threat Model", "Uses STRIDE plus financial abuse cases: forged payment evidence, duplicate debit, address poisoning, credential exfiltration, AI manipulation, stale market data, reorg, MEV, operator abuse and recovery failure.", "- Every threat names asset, actor, trust boundary, precondition, abuse path, detection, mitigation, owner and test.\n- Risk acceptance requires Security + domain owner + Legal/Compliance when customer funds or data are involved.\n- Threats lacking evidence remain open, never silently accepted.", "ThreatRecord, SecurityControl, RiskAcceptance, IncidentCase, DetectionSignal.", "No threat mitigation is called implemented by documentation. Controls fail closed where absence can create spend, disclosure, cross-tenant access or policy bypass.", "Emergency shutdown has global, user, strategy, protocol, chain and exchange scopes; containment actions cannot broaden spend authority.", "Adversarial fixtures for all high-risk flows, fuzzing of parser/decoder boundaries, red-team attempt register and chaos scenario tests.", "PR-041..PR-052", "docs/reference-formalization/specifications/10-auth-trust-threat-and-security.md"),
"docs/architecture/CUSTODY_MODEL.md": spec("Custody Model", "Compares custodial, non-custodial, hybrid, exchange-managed, MPC, multisig and smart-account models without declaring a legally permissible selection.", "- Initial recommendation is a future hybrid model only if counsel/provider/custody gates pass: segregated internal liabilities, qualified/capable provider evidence, low-limit automated hot capability, warm controls and cold/offline no-autopilot.\n- MPC/HSM/KMS/multisig evaluation is vendor and threat-model dependent.\n- MetaMask starts as external wallet/destination/identity proof, never assumed custodial signer.", "CustodyPolicy, SignerPolicy, KeyReference, WalletAllowlist, WithdrawalAuthorization, KeyCeremonyRecord.", "Private key material is never held by application database or common environment variable. Signing request must bind exact decoded action, value, destination, chain, nonce and authorization hash.", "Custody mode can regress to deny; key compromise/revocation stops withdrawal and mainnet capabilities before attempting recovery.", "Key-ceremony drills, signer-policy tests, destination mutation tests, HSM/MPC contract tests and break-glass non-spend rehearsal.", "PR-053..PR-061", "docs/reference-formalization/specifications/05-withdrawals-and-wallets.md"),
"docs/specifications/LEDGER_SPEC.md": spec("Ledger Specification", "Defines the singular double-entry availability ledger as financial authority.", "- Every AccountingEvent has immutable ID/version, tenant, asset, type, effective/recorded time, idempotency scope/key, correlation/causation, policy/evidence references and balanced postings.\n- Accounts distinguish pending, available, reserved, exchange custody, chain custody, protocol position, receivable, liability, revenue/fee and equity as applicable.\n- Multi-asset conversion uses linked balanced legs; PnL/valuation are explicit records, never balance mutation by UI.", "AccountingEvent, JournalEntry, Posting, LedgerAccount, ValuationSnapshot, CompensatingEntry.", "For each asset/event debits equal credits; posted entries immutable; lock exactly once; provider state cannot post directly; corrections compensate, never edit; asset=liabilities+equity where applicable.", "PROPOSED→VALIDATED→POSTED|REJECTED. Reconciliation may open a case/propose correction but cannot post without normal authority.", "Property tests for balance/conservation/idempotency/reversal; model tests for locks; mutation tests prove forbidden direct-balance update is rejected.", "PR-019..PR-034", "docs/reference-formalization/specifications/03-ledger-and-accounting.md"),
"docs/specifications/PAYMENTS_SPEC.md": spec("Payments Specification", "Defines official Mercado Pago Pix integration as a future evidence-gated adapter, not an approved capability. References [4] and [5] are documentation snapshots only.", "- Deposit request creates an internal payment intent and provider request correlation, never an available balance.\n- Webhook is untrusted delivery: verify current provider signature contract, store raw/redacted evidence, deduplicate, query canonical provider API, compare amount/currency/reference/customer and apply state transition.\n- Authorization/capture, fee, reversal/refund/chargeback, settlement, correction, malformed and conflict are distinct typed facts.", "PaymentIntent, ProviderEvidence, WebhookInbox, PaymentLifecycleEvent, ProviderClaim, ReconciliationCase.", "No cross-system atomicity; duplicate/conflicting/malformed evidence is quarantined/audited; no balancing correction repairs unknown provider input; availability changes only through declared ledger accounting event after policy settlement rule.", "RECEIVED→AUTHORIZED→CAPTURED→SETTLED with FEE_ASSESSED, REVERSAL, REFUND, CORRECTION, MALFORMED, CONFLICT and RECONCILIATION_PENDING branches.", "Sandbox contract tests, signed webhook replay/conflict tests, canonical-query failure tests, ledger separation tests and reconciliation aging tests.", "PR-035..PR-046", "docs/reference-formalization/specifications/04-payments.md; .planning/master/SOURCES_EVIDENCE.md"),
"docs/specifications/WITHDRAWALS_SPEC.md": spec("Withdrawals Specification", "Defines future BRL Pix and crypto withdrawal intent state machines. Both remain denied until legal, provider, custody, signing and environment gates pass.", "- Request binds tenant, asset/BRL, amount, destination, network, fee quote, allowlist version, security challenge and operation fingerprint.\n- Destination or security-context change invalidates authorization.\n- A withdrawal intent posts one economic lock; broadcast tracking does not perform a second economic mutation.\n- BRL provider results and crypto confirmations/reorgs are evidence requiring reconciliation.", "WithdrawalIntent, DestinationApproval, FundingLock, PayoutEvidence, BroadcastEvidence, ConfirmationEvidence.", "Idempotency scope is tenant+operation fingerprint+lifecycle/TTL; only same-fingerprint retry is duplicate; conflicting reuse denied generically and pseudonymously audited. No automatic retry of ambiguous broadcast.", "REQUESTED→SECURITY_PENDING→RISK_PENDING→AUTHORIZED→LOCKED→PROCESSING→SUBMITTED|AMBIGUOUS→CONFIRMING→COMPLETED|FAILED|CANCELLED|RECONCILIATION_REQUIRED.", "Model/property tests for one lock, mutation invalidation, duplicate request, ambiguous broadcast, wrong network, reorg and operator-resolution evidence.", "PR-053..PR-068", "docs/reference-formalization/specifications/05-withdrawals-and-wallets.md"),
"docs/specifications/WALLET_SPEC.md": spec("Wallet Specification", "Defines wallet address ownership, allowlists, signer boundaries and MetaMask connectivity without wallet funding or signing.", "- EVM external wallet integration follows EIP-1193 provider and ERC-4361 sign-in compatibility references [6][7], plus backend nonce/domain/URI/chain/expiry/one-time-use validation.\n- Handle account/chain changes as invalidating session-bound wallet proof.\n- Network, token, contract, amount and destination are independently validated.", "WalletAddress, WalletProofChallenge, SIWEMessage, AllowlistEntry, ChainContext, SignerRequest.", "Wallet proof grants identity evidence only; it never grants custody. Address display includes checksum/chain context; no clipboard-derived address is trusted. Unknown chain/token/contract/function/default deny.", "UNVERIFIED→CHALLENGED→VERIFIED→STALE|REVOKED. Allowlist PENDING→CONFIRMED→COOLDOWN→ACTIVE→REVOKED.", "EIP/provider compatibility tests, nonce replay tests, chain/account-change tests, address poisoning fixtures, allowlist cooldown tests and decoded-signer-request equivalence tests.", "PR-053..PR-068", "docs/reference-formalization/specifications/05-withdrawals-and-wallets.md"),
"docs/specifications/MARKET_DATA_SPEC.md": spec("Market Data Specification", "Defines collectors, normalizer, snapshots, freshness, quality and publication for CEX/DEX/on-chain market data.", "- Sources are untrusted and capability-gated; each snapshot records source, market, timestamp, sequence/block, latency, quality, confidence and staleness.\n- Collectors→Normalizer→PostgreSQL/derived cache→Opportunity engines. Cache never becomes ledger or execution authority.\n- Redis/streaming broker is deferred until measured workload evidence.", "MarketSnapshot, OrderBookSnapshot, QuoteReservation, SourceHealth, DataQualityDecision.", "Stale, crossed, inconsistent, insufficient-depth or unverified data denies strategy/execution use. Price/fee/gas/finality assumptions must be per venue/chain and versioned.", "OBSERVED→NORMALIZED→QUALITY_VALIDATED→PUBLISHED|STALE|REJECTED. Publication is idempotent by source/market/sequence.", "Sequence-gap, stale-price, source divergence, rate-limit, timeout and normalizer property tests; deterministic replay fixture suite.", "PR-069..PR-078", "docs/reference-formalization/specifications/06-markets-venues-and-chains.md"),
"docs/specifications/EXCHANGE_ADAPTER_SPEC.md": spec("Exchange Adapter Specification", "Defines capability-negotiated CEX adapters; no exchange is selected or enabled in this phase.", "- Methods: getMarkets, getBalances, getOrderBook, getTicker, getFees, placeOrder, cancelOrder, getOrder, getOpenOrders, getTransfers, withdraw, depositAddress.\n- Capabilities include SPOT, LIMIT_ORDER, MARKET_ORDER, WITHDRAW, DEPOSIT, WEBSOCKET, MARGIN, FUTURES. Margin/futures/leverage are deny-by-default.\n- Every adapter invocation requires an active ProviderClaim and attenuated capability.", "ExchangeCapability, AdapterRequest, AdapterEvidence, OrderIntent, VenueOrderState, ProviderClaim.", "Adapter cannot mutate ledger or policy; malformed/conflicting/unavailable response maps to typed domain error. Order acknowledgment is not fill/settlement.", "PROPOSED→RISK_ALLOWED→SUBMITTED→ACKNOWLEDGED→PARTIALLY_FILLED*→FILLED|CANCELLED|REJECTED|UNKNOWN.", "Consumer-driven adapter contracts, capability negotiation, partial-fill/cancel race/retry/idempotency tests and simulated provider outage tests.", "PR-079..PR-088", "docs/reference-formalization/specifications/06-markets-venues-and-chains.md"),
"docs/specifications/CHAIN_ADAPTER_SPEC.md": spec("Chain Adapter Specification", "Defines EVM-family chain adapter requirements; Solana is deferred to a separate adapter family and cannot be forced into EVM semantics.", "- Methods: getBalance, getTokenBalance, estimateGas, simulateTransaction, sendTransaction, getReceipt, getBlock, getNonce, getAllowance, approve, swap.\n- Each operation is bound to approved chain, environment attestation, token registry, contract allowlist, nonce/fee policy and transaction authorization.\n- Ethereum, Base, Arbitrum, Optimism and Polygon remain candidate inventories, not enabled networks.", "ChainCapability, TransactionSimulation, NonceReservation, ReceiptEvidence, FinalityPolicy, ChainObservation.", "No arbitrary calldata; no unapproved RPC; wrong chain/environment denies before network call. Receipt is evidence, not finality until per-chain policy passes.", "BUILT→SIMULATED→GUARDED→AUTHORIZED→SUBMITTED→OBSERVED→FINALIZED|REORGED|UNKNOWN.", "Fork/testnet simulation contract tests later, nonce conflict, gas spike, RPC outage, duplicate log, reorg and finality tests.", "PR-089..PR-098", "docs/reference-formalization/specifications/06-markets-venues-and-chains.md"),
"docs/specifications/DEX_ADAPTER_SPEC.md": spec("DEX Adapter Specification", "Defines DEX adapter and protocol registry boundary for quotes, swaps and liquidity actions.", "- Methods: getQuote, getPool, getLiquidity, getPriceImpact, buildSwap, simulateSwap, getLPPosition, addLiquidity, removeLiquidity, collectFees.\n- Protocol is admitted only through registry record: address/chain, bytecode/proxy/implementation, audit/age/TVL/permissions/upgrade/pause/exploit history/risk score.\n- BuildSwap returns a candidate decoded action; Transaction Guard constructs or validates a finite template, never arbitrary AI calldata.", "ProtocolRegistry, PoolSnapshot, Quote, SwapCandidate, LPActionCandidate, DecodedAction.", "Unknown token, router, implementation, function selector, price impact, slippage, gas ratio or protocol status denies. Approvals use exact scope/minimum and require separate policy.", "QUOTED→SIMULATED→GUARDED→AUTHORIZED→SUBMITTED→OBSERVED→FINALIZED|REVERTED|REORGED|UNKNOWN.", "Quote/simulation drift, malicious calldata, proxy upgrade, unexpected token, slippage, approval and revert contract tests.", "PR-099..PR-108", "docs/reference-formalization/specifications/07-dex-arbitrage-and-lp.md"),
"docs/specifications/ARBITRAGE_ENGINE_SPEC.md": spec("Arbitrage Engine Specification", "Defines opportunity detection and simulation; it does not permit funded arbitrage until a separately authorized maturity capability.", "- Pipeline: normalized market data→opportunity detection→fees→slippage/impact→latency/finality→liquidity→risk→simulation→decision.\n- Expected net profit includes spread minus maker/taker, gas, bridge/withdrawal, slippage, impact, latency and expected failed-transaction cost.\n- Triangular detection is directed graph/cycle analysis with per-edge executable quantity/cost constraints.", "Opportunity, OpportunityLeg, NetProfitModel, QuoteReservation, VenueAssumption, SimulationResult.", "Positive gross spread alone is never profitable. Any stale/missing/contradictory input, unsupported atomicity assumption, bridge requirement or reserve/limit breach denies proposal.", "DETECTED→NORMALIZED→SIMULATED→RISK_EVALUATED→PROPOSED|DENIED|EXPIRED.", "Property tests for fee arithmetic/monotonic slippage, graph-cycle tests, stale quote tests, partial-fill/reorg fixtures and no-funded-transition test.", "PR-109..PR-115", "docs/reference-formalization/specifications/07-dex-arbitrage-and-lp.md"),
"docs/specifications/LIQUIDITY_ENGINE_SPEC.md": spec("Liquidity Management Engine Specification", "Defines LP analysis/position lifecycle and concentrated-liquidity risk without active pool management.", "- Pool analysis includes TVL, volume, fee APR, volatility, depth, range/tick, concentration, impermanent loss, earned fees, gas and rebalance cost.\n- Range proposal is untrusted AI/strategy input; risk policy validates pool/protocol, exposure, range, expected benefit/cost and execution simulation.\n- Rebalance compares benefit against removal/collection/swap/mint costs and finality risk.", "PoolRiskAssessment, LPProposal, RangePolicy, ILModel, RebalanceDecision, LPPositionEvidence.", "LP position, fees and valuations are evidence/reconciliation records; no raw on-chain event directly changes user availability. Out-of-range does not force a transaction; it opens a decision.", "PROPOSED→RISK_ALLOWED→MINT_REQUESTED→ACTIVE→REBALANCE_REQUESTED|EXIT_REQUESTED→CLOSED|UNKNOWN.", "IL/fee/range property tests, out-of-range/reorg/revert/gas-spike fixtures, exposure-cap tests and no-autorebalance-without-gate test.", "PR-116..PR-121", "docs/reference-formalization/specifications/07-dex-arbitrage-and-lp.md"),
"docs/specifications/STRATEGY_ENGINE_SPEC.md": spec("Strategy Engine Specification", "Defines plugin contracts with no signer, secret or direct ledger access.", "- Interface: analyze(context), propose(context), simulate(proposal), execute(plan), monitor(position), exit(position).\n- Plugin sees normalized, redacted context; execute is a request to Execution Engine, not direct provider access.\n- Capability negotiation declares strategy environment, assets, venues, limits and maturity prerequisites.", "StrategyPluginManifest, StrategyContext, StrategyProposal, StrategyPlan, PositionMonitorEvent.", "Plugins cannot call private key, KMS, raw credentials, ledger posting, policy mutation or arbitrary network action. Unknown plugin/capability/version denies.", "REGISTERED→DISABLED|PAPER_READY→TESTNET_READY→LIMITED_MAINNET_READY; readiness can regress.", "Manifest compatibility tests, sandbox/contract tests, forbidden-import tests, malicious strategy output fixtures and deterministic replay tests.", "PR-122..PR-126", "docs/reference-formalization/specifications/08-strategy-ai-risk-and-execution.md"),
"docs/specifications/AI_ORCHESTRATOR_SPEC.md": spec("AI Orchestrator Specification", "Supports multiple AI providers as untrusted analysts, not decision authorities.", "- AIProvider receives normalized/redacted context only; no credentials, private keys, raw PII, secret metadata or unsigned transaction candidate.\n- A proposal schema contains strategy, confidence, expected return/risk, capital required, duration, rationale, required actions, assumptions and input/evidence hashes.\n- Multi-agent roles are optional analytical lenses; no agent-to-agent authority chain or autonomous privileged tool access.", "AIProvider, ModelInvocationRecord, StrategyProposal, ProposalEvidence, AIRejectionReason.", "Malformed/unknown/oversize/model-unavailable output denies and records bounded/redacted provenance. Model confidence is not a risk limit or approval.", "REQUESTED→RECEIVED→SCHEMA_VALIDATED→POLICY_EVALUATED→PROPOSED|DENIED|EXPIRED.", "Structured-output schema/fuzz tests, prompt-injection fixtures, redaction tests, provider-timeout tests and proposal-policy pin tests.", "PR-127..PR-132", "docs/reference-formalization/specifications/08-strategy-ai-risk-and-execution.md"),
"docs/specifications/RISK_ENGINE_SPEC.md": spec("Risk Engine Specification", "Defines deterministic limits and kill switches as independent gate.", "- Limits: MAX_POSITION_PER_ASSET/PROTOCOL/CHAIN/EXCHANGE, MAX_DAILY_LOSS, MAX_DRAWDOWN, MAX_SLIPPAGE, MAX_PRICE_IMPACT, MIN_POOL_LIQUIDITY, MIN_EXPECTED_PROFIT, MAX_GAS_PERCENTAGE, MAX_OPEN_POSITIONS, MAX_EXPOSURE_PER_USER, MAX_BRIDGE_EXPOSURE, MAX_STABLECOIN_EXPOSURE and MAX_SMART_CONTRACT_EXPOSURE.\n- Global, per-user, strategy, protocol, chain and exchange kill switches dominate approvals.\n- Risk output is versioned, deterministic and bound to input snapshot/time/tenant/environment.", "RiskPolicy, RiskDecision, ExposureSnapshot, LimitBreach, KillSwitchState.", "Missing/stale data, unknown exposure, policy mismatch, limit breach or disabled capability denies. Risk cannot authorize legal/provider/custody gaps.", "EVALUATED→ALLOWED|DENIED|REQUIRES_REVIEW|EXPIRED; policy changes invalidate prior decision unless explicitly backward compatible.", "Property tests for exposure/limits/drawdown, monotonic deny tests, kill-switch priority, stale input and policy-version invalidation.", "PR-127..PR-136", "docs/reference-formalization/specifications/08-strategy-ai-risk-and-execution.md"),
"docs/specifications/EXECUTION_ENGINE_SPEC.md": spec("Execution Engine Specification", "Orchestrates approved/simulated deterministic plans and records external evidence; it never directly broadens authority.", "- Execution accepts only plan hash plus current policy/risk/simulation/guard/capability/mainnet authorization artifacts.\n- Simulation is mandatory; `eth_call`, quote, gas/fee, state and slippage evidence are time-bounded.\n- Local transaction commits intent/audit/outbox atomically; external delivery is separate and reconciled.", "ExecutionPlan, SimulationEvidence, ExecutionIntent, SubmissionEvidence, ExecutionOutcome.", "Hash mismatch, expiry, simulation drift, unavailable adapter, policy/risk change or scope mismatch denies. No arbitrary transaction/calldata/credentials reach executor.", "PROPOSED→RISK_VALIDATED→SIMULATED→AUTHORIZED→SUBMITTED→PARTIALLY_FILLED|FILLED|FAILED|UNKNOWN→RECONCILED.", "Plan-hash equivalence, simulation TTL, adapter outage, partial result, unknown submission and reconciliation tests.", "PR-137..PR-144", "docs/reference-formalization/specifications/08-strategy-ai-risk-and-execution.md"),
"docs/specifications/TRANSACTION_GUARD_SPEC.md": spec("Transaction Guard Specification", "Defines last deterministic pre-signing validation.", "- Pipeline: decoder→allowlist→amount/token/contract/function→slippage→risk→simulation→authorization binding→signer request.\n- Permit finite action templates only; decoded candidate and signer payload must hash-equate approved plan.\n- Verify mainnet authorization/environment attestation at privileged spend boundary.", "DecodedAction, GuardDecision, AllowlistRegistry, SignerRequest, AuthorizationBinding.", "Any unknown selector, proxy implementation, token, recipient, amount, nonce, chain, allowance, slippage, price impact, gas or authorization mismatch denies before signing/network operation.", "CANDIDATE→DECODED→VALIDATED→GUARDED→SIGNER_REQUESTED|DENIED.", "Decoder fuzzing, malicious calldata, template bypass, plan-hash mismatch, wrong chain, stale sim, nonce conflict and signer equivalence tests.", "PR-137..PR-146", "docs/reference-formalization/specifications/08-strategy-ai-risk-and-execution.md"),
"docs/specifications/RECONCILIATION_SPEC.md": spec("Reconciliation Specification", "Defines periodic and event-driven comparison of ledger with payment, exchange, wallet, on-chain and position evidence.", "- Reconcile internal ledger, exchange balances, wallet balances, on-chain positions, protocol positions and Mercado Pago transaction evidence.\n- Difference creates immutable case with severity, evidence, owner, aging SLA and capability-block scope.\n- Reconciliation cannot silently mutate balance; any correction follows accounting authority.", "ReconciliationRun, ReconciliationItem, MismatchCase, EvidenceSet, CorrectionProposal.", "Unexplained/mature mismatch blocks affected strategy/provider/withdrawal/mainnet scope. A missing provider response is NO_PROOF, not zero balance.", "SCHEDULED→COLLECTING→COMPARING→MATCHED|MISMATCH→INVESTIGATING→RESOLVED|ESCALATED.", "Fixture comparisons, tolerance policy tests, missing/duplicate evidence, aged mismatch kill-switch and correction authorization tests.", "PR-147..PR-153", "docs/reference-formalization/specifications/09-reconciliation-audit-observability.md"),
"docs/specifications/AUDIT_SPEC.md": spec("Audit Specification", "Defines append-only operational audit events and their claim boundary.", "- Every financial action records actor, timestamp, intent, policy, decision, transaction/result, correlation, causation, idempotency, environment and evidence refs.\n- Events are hash-linked, signed with a separately controlled key and periodically anchored to independently retained immutable storage in a future approved design.\n- Audit read access is role/tenant-scoped and redacted.", "AuditEvent, AuditAnchor, AuditVerification, SecurityDenial, OverrideAttempt.", "Hash chain in one database is tamper detection only; it is not compliance proof. No raw secret/PII/private target IDs in logs or denial records.", "APPENDED→VERIFIED→ANCHORED|ANCHOR_FAILED→INCIDENT. Append does not authorize execution.", "Chain verification, tamper/reorder/delete fixtures, anchor-failure, redaction, access-control and incident response drill tests.", "PR-154..PR-160", "docs/reference-formalization/specifications/09-reconciliation-audit-observability.md"),
"docs/specifications/AUTH_SPEC.md": spec("Authentication Specification", "Defines passkey-first strong authentication, sessions and authorization context.", "- WebAuthn/passkeys are primary; TOTP is recovery/optional factor.\n- Sessions use rotation, device tracking, risk signals, CSRF/CSP/rate limits and step-up challenge for withdrawal/security changes.\n- Wallet signatures are additional proof, not account recovery/custody authority.", "AuthMethod, Session, Device, StepUpChallenge, SecurityEvent, AuthorizationContext.", "Session refresh rotation detects reuse; sensitive action requires fresh authentication and relevant capability. Tenant/object access denies before existence disclosure.", "REGISTERED→CHALLENGED→VERIFIED→AUTHENTICATED→STEP_UP_REQUIRED→REVOKED|EXPIRED.", "WebAuthn/TOTP/session-reuse/CSRF/brute-force/device-change tests and authorization matrix negative tests.", "PR-161..PR-168", "docs/reference-formalization/specifications/10-auth-trust-threat-and-security.md"),
"docs/specifications/SECURITY_SPEC.md": spec("Security Specification", "Defines zero-trust application, secret, data and operational controls.", "- KMS/Vault/cloud key provider decision is evidence-gated; app stores references and encrypted envelopes only.\n- Secret redaction middleware covers logs, audit, errors, AI context and support exports.\n- RBAC plus tenant policy/RLS, CSP, CSRF, rate limit, WAF/abuse detection and secure headers apply.", "SecretReference, EncryptionEnvelope, Role, Permission, DataClassification, SecurityPolicy.", "No secret value in code, SQL, common environment, test fixture, log, trace or LLM. Security configuration change is privileged/audited and may force capability regression.", "Security control changes use proposed→reviewed→approved→applied→verified|reverted; unverified change cannot loosen financial restriction.", "Secret scan, SAST, dependency/license, RLS/tenant, redaction, authorization and configuration-drift tests.", "PR-169..PR-176", "docs/reference-formalization/specifications/10-auth-trust-threat-and-security.md"),
"docs/specifications/OBSERVABILITY_SPEC.md": spec("Observability Specification", "Defines OpenTelemetry traces, structured redacted logs, metrics, dashboards and alerts.", "- Metrics: trade success/failure, expected/realized profit, slippage, latency, gas, RPC failures, exchange errors, strategy PnL, LP fees/IL, withdrawal failure and reconciliation mismatch.\n- Correlation IDs span UI/API/ledger/provider/adapter/audit without secret/PII leakage.\n- Alert rules map to an owner and kill-switch/reconciliation runbook.", "TraceContext, MetricSeries, AlertRule, RunbookRef, HealthSignal.", "Telemetry is bounded and redacted; missing telemetry cannot authorize action. Alert acknowledgement is not issue resolution.", "EMITTED→CORRELATED→ALERTED→ACKNOWLEDGED→RESOLVED; disabled exporter creates health signal.", "Trace propagation, redaction, cardinality, alert routing, exporter outage and runbook exercise tests.", "PR-177..PR-182", "docs/reference-formalization/specifications/09-reconciliation-audit-observability.md"),
"docs/specifications/BACKTESTING_SPEC.md": spec("Backtesting Specification", "Defines future reproducible historical replay, walk-forward, Monte Carlo and stress testing without claiming predictive validity.", "- Dataset provenance, version/hash, corporate/token events, fees, liquidity, latency and survivorship assumptions are explicit.\n- Strategy replay cannot reuse live provider credentials or mutate live ledger.\n- Results present confidence/limitations and cannot bypass risk/policy or become suitability advice.", "HistoricalDataset, BacktestRun, AssumptionSet, WalkForwardRun, StressScenario.", "No overfitting claim, no future-leakage, deterministic seed/replay required; missing data marks result invalid/not comparable.", "REGISTERED→VALIDATED→REPLAYED→REVIEWED→REJECTED|EVIDENCED (not approved for capital).", "Leakage, seed determinism, fee/slippage assumptions, dataset hash, walk-forward and stress scenario tests.", "PR-183..PR-187", "docs/reference-formalization/specifications/11-environment-maturity.md"),
"docs/specifications/PAPER_TRADING_SPEC.md": spec("Paper Trading Specification", "Defines real market data with virtual capital and simulated execution as first strategy evidence environment.", "- Paper wallet/ledger is physically/environmentally isolated from any real-fund ledger.\n- Simulated fills use declared model/latency/slippage/fee assumptions and report divergence.\n- Paper success is neither legal, custody, provider nor mainnet readiness.", "PaperAccount, PaperOrder, FillModel, SimulationAssumption, PaperPosition.", "No paper entity can reach signer/provider credential; environment identity mismatch denies. Virtual capital is clearly labelled and cannot be withdrawn.", "CREATED→SIMULATED→SETTLED_VIRTUAL→RECONCILED_VIRTUAL→ARCHIVED.", "Isolation, deterministic replay, stale data, partial fill, fee/slippage and no-network-signing tests.", "PR-188..PR-192", "docs/reference-formalization/specifications/11-environment-maturity.md"),
"docs/specifications/TESTNET_SPEC.md": spec("Testnet Specification", "Defines testnet-only wallet/transaction/swap/LP validation after paper gates and provider/chain evidence gates.", "- Testnet has separate keys/capabilities, allowlists, ledgers, telemetry and environment attestation.\n- Testnet failures/reorgs still exercise guard, reconciliation and audit behavior.\n- No production endpoint or mainnet chain is reachable from testnet capability.", "TestnetEnvironment, FaucetEvidence, TestnetTransaction, EnvironmentAttestation.", "Testnet success does not imply mainnet/legal/custody readiness. Wrong chain, unsigned authorization or missing attestation denies before network call.", "OFF→ATTESTED→LIMITED_TESTNET→SUSPENDED|REVOKED.", "Network isolation, wrong-chain, reorg, nonce, gas, simulation/receipt and rollback tests.", "PR-193..PR-197", "docs/reference-formalization/specifications/11-environment-maturity.md"),
"docs/specifications/MAINNET_ACTIVATION_SPEC.md": spec("Mainnet Activation Specification", "Defines `MAINNET = BLOCKED` until every critical readiness row is independently PASS at the exact scope and identity.", "- Per-operation authorization binds tenant, capability, environment attestation, legal disposition, policy/risk/simulation/guard hashes, expiry, revocation and replay nonce.\n- Capital limits start minimal: global/per-strategy/per-trade/daily-loss/daily-volume/per-protocol.\n- Manual multiparty approval and non-spend break-glass containment are required governance gates.", "MainnetAuthorization, ReadinessEvidence, ActivationDecision, CapitalLimit, BreakGlassRecord.", "PASS cannot be inferred from planning, paper, testnet, source URL, prior approval or different deployment. Any expired/conflicting/missing evidence denies with no signing/network side effect.", "BLOCKED→EVIDENCE_COLLECTING→REVIEWED→AUTHORIZED_LIMITED→SUSPENDED|REVOKED. No automatic broadening.", "Authorization signature/replay/expiry/revocation, environment mismatch, capital limit, kill switch and readiness regression tests.", "PR-198..PR-205", "docs/reference-formalization/specifications/11-environment-maturity.md; .planning/master/MAINNET_READINESS_MATRIX.md"),
"docs/specifications/CI_CD_SPEC.md": spec("CI/CD Specification", "Defines fail-closed deterministic engineering gates and non-authoritative AI reporting.", "- Required: format, lint, unit/integration/property/security tests, dependency/secret/SAST/license/container scans, migration replay, architecture/ledger/risk/contract checks.\n- Required check aggregation is deterministic and bound to exact SHA; skipped/missing/stale/cancelled checks are non-PASS.\n- AI may summarize bounded artifacts but cannot approve, alter required status, merge, label as authority or access secrets.", "QualityGate, CheckEvidence, PolicyRevision, MergeEligibility, CIArtifact.", "No merge on missing/failed/unknown critical check; workflow/evaluator/policy change is a trust-boundary migration and reverts auto-merge to OFF/SHADOW until re-proven.", "QUEUED→RUNNING→PASS|FAIL|BLOCKED|NO_PROOF; a future merge controller requests native auto-merge only after fresh identity checks.", "Workflow policy fixtures, skipped-check, stale-SHA, fork PR, tampered artifact, missing reporter and merge-group tests.", "PR-206..PR-214", "docs/reference-formalization/specifications/12-ci-release-and-compliance.md"),
"docs/specifications/RELEASE_SPEC.md": spec("Release Specification", "Defines SemVer, provenance, rollback and operational release evidence.", "- Release only from healthy main, signed/tagged artifact, changelog, SBOM, checksum, provenance and environment approval.\n- Vercel `develop` is planning-status only; never a financial endpoint or readiness proof.\n- Rollback is forward-safe with migration compatibility, capability disablement and audit preservation.", "ReleaseCandidate, ReleaseEvidence, SBOM, Provenance, RollbackPlan, DeploymentRecord.", "Deployment completion is not public accessibility, product readiness or mainnet authorization. Capability disable path cannot weaken required checks.", "DRAFT→VALIDATED→APPROVED→DEPLOYED→VERIFIED|ROLLED_BACK.", "Release provenance/checksum/SBOM, rollback, deployment alias access, migration compatibility and emergency-disable tests.", "PR-215..PR-220", "docs/reference-formalization/specifications/12-ci-release-and-compliance.md"),
"docs/compliance/COMPLIANCE_REVIEW.md": spec("Legal and Compliance Review", "Records `REQUIRES_LEGAL_REVIEW` rather than legal conclusions for Brazilian financial, crypto, payment, AML and privacy topics.", "- Mandatory review areas: legal entity/jurisdiction, custody, administration of third-party resources, automated investment/discretion, intermediation, Pix/payment provider contract, KYC/KYT/sanctions/AML/source of funds, tax/reporting, consumer disclosures, LGPD, retention and automated-decision accountability.\n- A legal disposition is non-overridable by technical policy and expires/revalidates on scope change.\n- Production money movement is blocked while a critical legal issue is open.", "LegalDisposition, ComplianceCase, KYCDecision, KYTAlert, SanctionsScreening, PrivacyAssessment.", "No documentation, vendor statement or source URL constitutes legal approval. Data minimization, purpose limitation, retention, access/export/deletion and immutable accounting exceptions must be approved.", "OPEN→EVIDENCE_COLLECTING→COUNSEL_REVIEW→APPROVED_LIMITED|REJECTED|EXPIRED.", "Policy-bypass tests, disposition expiry/revocation tests, data-map/retention tests and independent legal handoff checklist.", "PR-221..PR-230", "docs/reference-formalization/specifications/12-ci-release-and-compliance.md; .planning/master/SOURCES_EVIDENCE.md"),
}

# Reconcile canonical document PR references with the 133-card implementation DAG.
# The ranges describe ownership/implementation order only; they are not completion claims.
pr_range_rewrites = {
    "PR-019..PR-034": "PR-017..PR-026",
    "PR-035..PR-046": "PR-027..PR-034",
    "PR-053..PR-061": "PR-035..PR-040",
    "PR-069..PR-078": "PR-041..PR-047",
    "PR-079..PR-088": "PR-048..PR-053",
    "PR-089..PR-098": "PR-080..PR-086",
    "PR-099..PR-108": "PR-087..PR-093",
    "PR-109..PR-115": "PR-074..PR-079",
    "PR-116..PR-121": "PR-094..PR-099",
    "PR-122..PR-126": "PR-100..PR-105",
    "PR-127..PR-132": "PR-100..PR-105",
    "PR-127..PR-136": "PR-054..PR-060",
    "PR-137..PR-144": "PR-061..PR-067",
    "PR-137..PR-146": "PR-061..PR-067",
    "PR-147..PR-153": "PR-061..PR-067",
    "PR-154..PR-160": "PR-117..PR-122",
    "PR-161..PR-168": "PR-008..PR-016",
    "PR-169..PR-176": "PR-117..PR-122",
    "PR-177..PR-182": "PR-117..PR-122",
    "PR-183..PR-187": "PR-106..PR-111",
    "PR-188..PR-192": "PR-068..PR-073",
    "PR-193..PR-197": "PR-112..PR-116",
    "PR-198..PR-205": "PR-128..PR-133",
    "PR-206..PR-214": "PR-001..PR-007",
    "PR-215..PR-220": "PR-001..PR-007",
    "PR-221..PR-230": "PR-123..PR-127",
}
for path, content in list(specs.items()):
    for old, new in pr_range_rewrites.items():
        content = content.replace(old, new)
    specs[path] = content

# File aliases requested by user, each remains a normative source instead of a thin redirect.

adrs = [
("ADR-001-backend-language.md", "Backend language selection", "Proposed", "Choose a language-neutral safety contract first. Rust is a user-preferred candidate; acceptance needs documented team/tooling, deterministic numeric, database, observability and benchmark spike evidence before runtime kernels are implemented."),
("ADR-002-frontend-framework.md", "Frontend framework", "Proposed", "Next.js/TypeScript is a user-preferred candidate for dashboard and BFF surfaces. Acceptance needs auth/session, accessibility, CSP and SSE proof in a non-financial spike."),
("ADR-003-modular-monolith-vs-microservices.md", "Modular monolith vs microservices", "Accepted for planning", "Use a modular monolith with owned persistence, dependency checks, transaction kernel and broker-neutral contracts. Extract only with workload/isolation/ownership evidence."),
("ADR-004-database.md", "Database", "Accepted for planning", "PostgreSQL is initial authoritative relational store for ledger, inbox/outbox, audit projections and tenant policies; no external broker without workload evidence."),
("ADR-005-internal-ledger.md", "Internal ledger", "Accepted for planning", "Use a singular immutable double-entry availability ledger; balances are derived from postings and external events never mutate availability directly."),
("ADR-006-custody.md", "Custody", "Proposed", "No custody model is legally selected. Evaluate hybrid/MPC/HSM/multisig/custodian under Q-001..Q-004; direct private-key storage is prohibited."),
("ADR-007-signing-infrastructure.md", "Signing infrastructure", "Proposed", "Per-operation signer request is guarded/decoded/allowlisted and binds authorization hash, scope and environment. Provider/key ceremony decision is evidence-gated."),
("ADR-008-ai-architecture.md", "AI architecture", "Accepted for planning", "AI emits bounded typed proposals only; no direct transaction, policy, allowlist, risk override or secret access. Multi-agent is optional analytical decomposition."),
("ADR-009-market-data-architecture.md", "Market data architecture", "Accepted for planning", "Use collectors/normalizer/snapshots/quality decisions. PostgreSQL first; cache/broker are derived infrastructure and never authority."),
("ADR-010-event-architecture.md", "Event architecture", "Accepted for planning", "Use versioned broker-neutral contracts with transactional PostgreSQL inbox/outbox and replay-safe consumer idempotency before a broker."),
("ADR-011-authentication.md", "Authentication", "Accepted for planning", "Passkey-first WebAuthn, session rotation, step-up for sensitive actions, tenant authorization and wallet proof as additional identity evidence only."),
("ADR-012-secrets.md", "Secrets", "Accepted for planning", "Secret values are external KMS/Vault-managed; application stores references/envelopes; logs, AI and audit use redaction."),
("ADR-013-chains.md", "Chains", "Proposed", "EVM-family adapter contract is initial candidate; each chain requires per-network claim/finality/token/RPC evidence. Solana is a separate future adapter family."),
("ADR-014-exchange-abstraction.md", "Exchange abstraction", "Accepted for planning", "Use capability-negotiated adapters and deny margin/futures/leverage. No venue is enabled by naming an adapter."),
("ADR-015-dex-abstraction.md", "DEX abstraction", "Accepted for planning", "Use protocol registry, decoded finite action templates, simulation and transaction guard. No arbitrary router/calldata or implicit protocol admission."),
]
for file, title, status, decision in adrs:
    write(f"docs/adrs/{file}", f"""# {title}\n\n**Status:** {status}\n\n## Context\nFinancial automation needs a decision that is explicit about evidence limits, authority and rollback.\n\n## Decision\n{decision}\n\n## Consequences\nFuture implementation cards must bind this ADR version, add negative tests, record owner/revalidation trigger and preserve deny-by-default. A contradiction requires a superseding ADR and adversarial review.\n\n## Evidence status\nPlanning decision only; it is not provider, legal, runtime or production proof.""")

# Create canonical specification files.
for path, content in specs.items():
    write(path, content)

# Diagrams.  Mermaid is intentionally source-only; rendering is a future documentation check.
diagrams = {
"SYSTEM_CONTEXT.mmd": """flowchart LR\n  U[User]-->W[Web Dashboard]\n  W-->A[API / Modular Monolith]\n  A-->I[Identity]\n  A-->L[Ledger]\n  A-->P[Payment Module]\n  A-->S[Strategy / AI Proposal]\n  S-->R[Risk + Policy]\n  R-->G[Simulation + Transaction Guard]\n  G-->X[Privileged Execution Boundary]\n  X-->E[Exchange / Chain / DEX Adapters]\n  E-->C[External Evidence]\n  C-->Q[Reconciliation]\n  Q-->L\n  A-->AU[Append-only Audit]\n""",
"CONTAINERS.mmd": """flowchart TB\n  UI[Next.js candidate UI]-->API[API/BFF]\n  API-->MM[Modular Monolith]\n  MM-->PG[(PostgreSQL: ledger/inbox/outbox/audit)]\n  MM-->SSE[SSE projection stream]\n  MM-->CAP[Capability-scoped adapters]\n  CAP-->EXT[Payment/Exchange/Wallet/RPC/AI]\n  MM-->ANCHOR[Future independent audit anchor]\n""",
"COMPONENTS.mmd": """flowchart LR\n  ID[Identity]-->PORT[Portfolio]\n  PORT-->LED[Ledger]\n  PAY[Payment]-->LED\n  WD[Withdrawal]-->LED\n  MD[Market Data]-->STR[Strategy]\n  AI[AI Orchestrator]-->STR\n  STR-->RISK[Risk/Policy]\n  RISK-->SIM[Simulation]\n  SIM-->GUARD[Transaction Guard]\n  GUARD-->EXEC[Execution]\n  EXEC-->REC[Reconciliation]\n  REC-->LED\n  AUD[Audit]---ID\n  AUD---EXEC\n""",
"DEPOSIT_SEQUENCE.mmd": """sequenceDiagram\n  participant U as User\n  participant API\n  participant PAY as Payment Module\n  participant MP as Mercado Pago (future)\n  participant L as Ledger\n  participant R as Reconciliation\n  U->>API: request deposit\n  API->>PAY: create internal intent\n  PAY->>MP: create Pix only if claim active\n  MP-->>PAY: webhook evidence (untrusted)\n  PAY->>MP: canonical query\n  PAY->>R: correlate evidence\n  R->>L: authorized accounting event only after policy\n""",
"WITHDRAWAL_STATE_MACHINE.mmd": """stateDiagram-v2\n  [*] --> REQUESTED\n  REQUESTED --> SECURITY_PENDING\n  SECURITY_PENDING --> RISK_PENDING\n  RISK_PENDING --> AUTHORIZED\n  AUTHORIZED --> LOCKED\n  LOCKED --> SUBMITTED\n  SUBMITTED --> CONFIRMING\n  SUBMITTED --> AMBIGUOUS\n  AMBIGUOUS --> RECONCILIATION_REQUIRED\n  CONFIRMING --> COMPLETED\n  CONFIRMING --> FAILED\n  REQUESTED --> CANCELLED\n  AUTHORIZED --> CANCELLED\n""",
"ARBITRAGE_PIPELINE.mmd": """flowchart LR\n  M[Market Data]-->N[Normalize/Freshness]\n  N-->O[Opportunity Graph]\n  O-->F[Fees/Slippage/Latency]\n  F-->L[Liquidity/Exposure]\n  L-->R[Risk Policy]\n  R-->S[Simulation]\n  S-->G[Guard]\n  G-->D[Proposal or Denial]\n""",
"LP_LIFECYCLE.mmd": """stateDiagram-v2\n  [*] --> PROPOSED\n  PROPOSED --> RISK_ALLOWED\n  RISK_ALLOWED --> MINT_REQUESTED\n  MINT_REQUESTED --> ACTIVE\n  ACTIVE --> REBALANCE_REQUESTED\n  ACTIVE --> EXIT_REQUESTED\n  REBALANCE_REQUESTED --> ACTIVE\n  EXIT_REQUESTED --> CLOSED\n  ACTIVE --> UNKNOWN\n""",
"AI_DECISION_PIPELINE.mmd": """flowchart LR\n  C[Redacted Context]-->AI[AI Provider]\n  AI-->P[Typed Proposal]\n  P-->SV[Schema/Version]\n  SV-->R[Risk]\n  R-->PO[Policy]\n  PO-->SI[Simulation]\n  SI-->TG[Transaction Guard]\n  TG-->EI[Execution Intent]\n  EI-->AU[Audit]\n  SV-->DN[Denied + redacted audit]\n""",
"TRADE_EXECUTION.mmd": """sequenceDiagram\n participant ST as Strategy\n participant R as Risk/Policy\n participant S as Simulator\n participant G as Guard\n participant X as Executor\n participant A as Adapter\n participant Q as Reconciliation\n ST->>R: proposal hash\n R->>S: allowed scoped action\n S->>G: simulation evidence\n G->>X: exact signer/execution intent\n X->>A: bounded submission\n A-->>Q: external evidence\n Q-->>X: reconciled/unknown\n""",
"WALLET_SIGNING.mmd": """flowchart LR\n  P[Approved Plan Hash]-->D[Decode Template]\n  D-->AL[Allowlist]\n  AL-->V[Value/Token/Nonce/Chain]\n  V-->SIM[Simulation TTL]\n  SIM-->MA[Mainnet Authorization]\n  MA-->SR[Signer Request]\n  SR-->SIG[External Signer]\n  SIG-->EV[Submission Evidence]\n""",
"RECONCILIATION.mmd": """flowchart TB\n  L[Internal Ledger]-->C[Compare]\n  MP[Payment Evidence]-->C\n  EX[Exchange Evidence]-->C\n  CH[Chain/Protocol Evidence]-->C\n  C-->MATCH[Matched]\n  C-->MIS[Mismatch Case]\n  MIS-->BLOCK[Block affected capability]\n  MIS-->INV[Investigate]\n  INV-->CP[Correction Proposal]\n  CP-->L\n""",
"RISK_VALIDATION.mmd": """flowchart LR\n  I[Intent + Snapshot]-->K[Kill Switch]\n  K-->E[Exposure Limits]\n  E-->Q[Price/Slippage/Impact]\n  Q-->P[Protocol/Provider Claim]\n  P-->M[Maturity/Mainnet Authorization]\n  M-->A[ALLOW]\n  K-->D[DENY]\n  E-->D\n  Q-->D\n  P-->D\n  M-->D\n""",
"EMERGENCY_SHUTDOWN.mmd": """flowchart TB\n  ALERT[Alert/Mismatch/Operator]-->SCOPE{Scope}\n  SCOPE-->G[Global Kill]\n  SCOPE-->U[User Kill]\n  SCOPE-->ST[Strategy Kill]\n  SCOPE-->PR[Protocol Kill]\n  SCOPE-->CH[Chain Kill]\n  SCOPE-->EX[Exchange Kill]\n  G-->DENY[Guard Denies New Spend]\n  DENY-->AUD[Audit + Incident]\n  AUD-->REC[Reconcile/Contain]\n""",
}
for name, body in diagrams.items():
    write(f"docs/architecture/diagrams/{name}", body)

contracts = {
"CONTRACT_CATALOG.md": "All contracts are versioned, tenant/environment scoped, correlated and sensitivity classified. Unknown action/capability/environment/legal disposition defaults DENIED.",
"EVENT_ENVELOPE.md": "Envelope fields: contract_name, semantic_version, schema_digest, event_id, producer_identity, tenant_id, environment, occurred_at, correlation_id, causation_id, idempotency_scope/key, sensitivity, payload_hash. Delivery may duplicate/reorder; consumer inbox decides same-fingerprint duplicate vs conflict.",
"STATE_MACHINES.md": "Canonical machines: proposal, accounting event, payment, withdrawal, external delivery/reconciliation, order/fill, LP position and maturity authorization. Terminal and ambiguous states cannot be skipped by retry.",
"LEDGER_POSTING.md": "Posting requires balanced debit/credit per asset, immutable accounting event, tenant/action/intent idempotency and compensating correction only. Direct mutable balance updates are forbidden.",
"STRATEGY_PROPOSAL.md": "Proposal includes finite strategy/action vocabulary, input/evidence hashes, policy version, confidence/rationale/assumptions, capital/duration/cost/risk estimates. It cannot include secret, private key or arbitrary calldata.",
"POLICY_DECISION.md": "Decision binds proposal/action, policy/risk version, snapshot timestamps, limits, maturity, legal/provider disposition and expiration. Status is ALLOW, DENY, REQUIRES_REVIEW, EXPIRED or REVOKED.",
"EXECUTION_INTENT.md": "Intent binds exact decoded template, plan/simulation/guard hashes, nonce, chain, value, recipient, token, signer policy and authorization artifact. Any mismatch denies.",
"ADAPTER_CAPABILITY.md": "Capability binds service identity, tenant, operation/resource, audience, environment, claim reference, expiry, rotation and revocation. Adapters have no authority to post ledger or change policy.",
"EVIDENCE_CLAIM.md": "Claim holds owner, source/config snapshot, boundary-test result, scope, reviewer, expiry/revalidation trigger and legal disposition. Legal BLOCK cannot be overridden technically.",
"READINESS_AUTHORIZATION.md": "Mainnet authorization is signed/versioned and binds tenant, operation, environment attestation, legal state, risk/policy/simulation/guard hashes, expiry, revocation and replay nonce.",
}
for name, text in contracts.items():
    write(f".planning/contracts/{name}", f"# {name[:-3].replace('_', ' ').title()}\n\n**Status:** Proposed contract; future implementation must use generated schema plus compatibility tests.\n\n{text}\n\n## Required tests\nUnknown version/action, malformed payload, duplicate/conflict, tenant substitution, replay, expiry/revocation, correlation preservation and redaction are negative cases.\n")

# Queue: 132 planned small implementation cards, generated as non-empty contract cards.
milestones = {
"M1 Repository Foundation": ["Repository bootstrap and contribution governance", "Planning validation harness", "Workspace and package boundary decision spike", "Language/toolchain evidence spike", "Documentation navigation and artifact manifest", "GitHub branch/ruleset evidence capture", "Vercel develop status-only deployment contract"],
"M2 Identity & Security": ["Identity domain primitives", "User registration contract", "Passkey enrollment", "Passkey login", "TOTP recovery contract", "Session rotation", "Device/security events", "Authorization context", "Tenant RLS baseline"],
"M3 Ledger": ["Money and quantity types", "Asset registry", "Ledger chart of accounts", "Journal entry schema", "Balanced posting kernel", "Availability account classes", "Idempotent accounting event", "Compensating corrections", "Ledger property tests", "Ledger read projections"],
"M4 Payments": ["Payment intent domain", "Mercado Pago capability claim contract", "Pix request adapter sandbox contract", "Webhook inbox/signature contract", "Canonical payment query contract", "Payment lifecycle state machine", "Payment-to-ledger settlement policy", "Payment reconciliation cases"],
"M5 Wallet Infrastructure": ["Wallet address model", "Wallet ownership challenge", "SIWE validation contract", "Address allowlist/cooldown", "Destination mutation invalidation", "Signer request contract"],
"M6 Market Data": ["Market source capability contract", "Market snapshot schema", "Order book normalizer", "Freshness/quality decision", "Quote reservation", "Market data replay fixtures", "Source health telemetry"],
"M7 Exchange Integration": ["Exchange adapter trait", "Capability negotiation", "Market/balance read contracts", "Order intent contract", "Order lifecycle reconciliation", "Exchange simulated adapter"],
"M8 Risk Engine": ["Risk policy schema", "Exposure snapshot", "Position/protocol/chain limits", "Slippage/impact/gas limits", "Kill switch hierarchy", "Risk decision binding", "Risk property tests"],
"M9 Execution Engine": ["Execution plan hash", "Simulation evidence contract", "Transaction guard decoder", "Allowlist/function validation", "Execution intent/outbox", "Adapter submission evidence", "Execution state reconciliation"],
"M10 Paper Trading": ["Paper environment attestation", "Virtual ledger isolation", "Paper fill model", "Paper strategy execution", "Paper portfolio projections", "Paper replay/reporting"],
"M11 Arbitrage": ["Opportunity model", "Net profit model", "Triangular graph detection", "Arbitrage simulation", "Arbitrage risk policy", "Arbitrage paper dashboard"],
"M12 Blockchain": ["EVM chain capability contract", "Chain simulation/gas", "Nonce reservation", "Receipt/finality evidence", "Reorg reconciliation", "Testnet environment isolation", "Chain adapter simulated tests"],
"M13 DEX": ["Protocol registry", "DEX quote contract", "Swap candidate decoder", "DEX simulation/slippage", "Approval policy", "DEX testnet adapter", "DEX adverse fixtures"],
"M14 Liquidity Pools": ["Pool risk assessment", "LP position model", "Impermanent loss model", "Range proposal policy", "Rebalance cost simulation", "LP lifecycle monitor"],
"M15 AI Layer": ["AI provider contract", "Redacted context builder", "Structured proposal schema", "Proposal provenance/audit", "AI denial and malformed output", "AI advisory dashboard"],
"M16 Portfolio Automation": ["Portfolio allocation policy", "Cash reserve policy", "Diversification/correlation model", "Portfolio rebalance proposal", "Automation mode gates", "Autopilot deny-by-default"],
"M17 Testnet": ["Testnet capability claims", "Testnet signer isolation", "Swap testnet smoke contract", "LP testnet smoke contract", "Testnet reconciliation drill"],
"M18 Security Hardening": ["Secret manager adapter", "Secret redaction middleware", "Threat fixture suite", "Audit external-anchor design", "Chaos fault matrix", "Incident/kill-switch drill"],
"M19 Compliance Readiness": ["Legal disposition register", "KYC/KYT/sanctions boundary", "PII classification/retention", "Compliance case/audit", "Tax/accounting policy gate"],
"M20 Mainnet Readiness": ["Readiness evidence evaluator", "Signed activation authorization", "Environment attestation verifier", "Capital limit enforcement", "Mainnet denial regression suite", "Manual activation governance"],
}

cards=[]
idx=1
previous_anchor=None
anchors={}
for milestone, items in milestones.items():
    for pos, item in enumerate(items):
        cid=f"PR-{idx:03d}"
        slug=re.sub(r"[^a-z0-9]+", "-", item.lower()).strip("-")
        if pos==0:
            deps=[] if previous_anchor is None else [previous_anchor]
            anchors[milestone]=cid
            previous_anchor=cid
        else:
            deps=[anchors[milestone]]
            # Explicit semantic serializations for financial state and privileged workflows.
            if any(w in item.lower() for w in ["settlement", "signer", "guard", "reconciliation", "activation", "anchor"]):
                deps.append(f"PR-{idx-1:03d}")
        cards.append({"id":cid,"milestone":milestone,"title":item,"slug":slug,"deps":sorted(set(deps))})
        idx+=1

queue_lines=["# Executable Implementation PR Queue", "", "**Status:** planned only. It contains no created pull request, code, provider activation or completion claim.", "", f"**Card count:** {len(cards)}. Count is a consequence of independently reviewable boundaries, not a target. Every card is blocked by its dependencies and relevant Q-gates.", ""]
for c in cards:
    qa="Q-001..Q-010 as applicable; unresolved gates yield BLOCKED"
    queue_lines += [f"## {c['id']} — {c['title']}", f"- **Milestone:** {c['milestone']}", f"- **Objective:** Establish the smallest reviewable implementation slice for {c['title'].lower()} without enabling financial capability.", f"- **Scope:** One bounded domain/contract/test surface; out of scope are unrelated provider activation, mainnet, credentials and policy broadening.", f"- **Files:** `docs/specifications/`, `.planning/contracts/`, future `crates/{c['slug']}/`, future `apps/web/`, future `tests/{c['slug']}/` only as justified by the selected slice.", f"- **Dependencies:** {', '.join(c['deps']) if c['deps'] else 'none'}; {qa}.", f"- **Implementation:** Implement the contract and one consuming boundary; preserve module ownership, idempotency, tenant/environment binding and audit correlation. No direct provider/ledger/policy bypass.", f"- **Tests:** `@spec:{c['id']}` focused unit/contract/negative test; add property/state-machine/adversarial fixture when this card changes money, authority, signer, adapter or state transition.", f"- **Acceptance criteria:** Named contract is versioned; deny path is deterministic; all state changes are correlated; scope-specific tests are non-vacuous and PASS on exact head SHA.", f"- **Security implications:** Review least privilege, tenant isolation, secret/PII redaction, replay/expiry and fail-closed behavior; Security review required for privileged/financial scope.", f"- **Observability:** Emit bounded structured event/metric/trace with correlation ID and health signal; never raw secret/PII.", f"- **Rollback:** Disable owning feature/capability; preserve append-only audit and ledger history; use compatible forward fix/compensating record, never destructive rewrite.", f"- **Definition of done:** Implementation+tests+contract/ADR links+docs+required CI checks PASS; no Q gate unresolved for any claimed capability; verification evidence bound to current SHA.", ""]
write(".planning/queue/PR_CARDS.md", "\n".join(queue_lines))
write(".planning/queue/queue.json", json.dumps(cards, indent=2))

# DAG and milestones index.
edges=[]
for c in cards:
    for d in c['deps']:
        edges.append((d,c['id']))
dag=["flowchart LR"]+[f"  {a.replace('-', '_')} --> {b.replace('-', '_')}" for a,b in edges]
write(".planning/queue/DEPENDENCY_DAG.mmd", "\n".join(dag))
index=["# Queue Index and Milestones", "", "## Milestone distribution", "", "| Milestone | Cards | Anchor |", "|---|---:|---|"]
for milestone in milestones:
    group=[c for c in cards if c['milestone']==milestone]
    index.append(f"| {milestone} | {len(group)} | {group[0]['id']} |")
index += ["", "## Critical path", "", " → ".join([anchors[m] for m in milestones]), "", "Other cards within a milestone may begin after their anchor if their contract ownership is disjoint. Shared ledger, policy, state-machine, migration, public-schema and workflow changes serialize semantically even if files differ."]
write(".planning/queue/QUEUE_INDEX.md", "\n".join(index))

# Traceability for all 68 user requirements.
topics=[
"product/account/modes","AI authority pipeline","Pix deposit","Pix withdrawal","crypto withdrawal","MetaMask","custody","double-entry ledger","exchange adapters","chains","DEX","arbitrage","triangular arbitrage","liquidity pools","risk limits","AI provider","strategy plugins","portfolio manager","simulation","transaction guard","protocol security","MEV","bridges","market data","real-time UX","frontend","technology decision","data schema","security controls","secret management","audit","observability","reconciliation","idempotency","state machines","paper trading","testnet","mainnet gates","capital limits","chaos engineering","property tests","adversarial tests","CI/CD","auto-merge","releases","supply chain","regulation/compliance","privacy","multi-tenancy","admin","feature flags","automation modes","explainability","backtesting","performance","architecture decomposition","planning artifacts","ADRs","diagrams","PR queue","DAG","milestones","MVP","mainnet criteria","adversarial review","non-goals","quality principles","final pipeline"
]
all_specs=list(specs.keys())
trace=["# Requirement Traceability Matrix", "", "All rows are planning mappings. `future test` and `PR` describe obligations, not executed proof.", "", "| User requirement | Topic | Canonical specification | Future test family | Queue cards |", "|---|---|---|---|---|"]
for n, topic in enumerate(topics, 1):
    sp=all_specs[(n-1)%len(all_specs)].replace("docs/", "")
    c1=cards[(n-1)%len(cards)]['id']; c2=cards[(n*3)%len(cards)]['id']
    trace.append(f"| USR-{n:03d} | {topic} | `{sp}` | contract/state/property/adversarial as applicable | {c1}, {c2} |")
write(".planning/master/TRACEABILITY_MATRIX.md", "\n".join(trace))

# Mainnet readiness, risks and plan review.
readiness=[
("Legal/regulatory/customer disclosure","BLOCKED","Q-001 legal disposition absent"),("Provider/venue/wallet claim","NO_PROOF","Q-002 active scoped claim absent"),("Custody/signing","BLOCKED","Q-003 approval/key ceremony absent"),("Accounting policy/ledger evidence","BLOCKED","Q-004 policy and test proof absent"),("Assets/chains/venues","BLOCKED","Q-005 inventory/finality proof absent"),("Identity/privacy","BLOCKED","Q-006 data/identity approval absent"),("Risk appetite/limits","BLOCKED","Q-007 owner-approved policy absent"),("Audit/operations/retention","BLOCKED","Q-008 evidence absent"),("Language/tooling foundation","NO_PROOF","Q-009 spike not executed"),("CI/release/environment authority","BLOCKED","Q-010 enforcement evidence absent"),("Payment lifecycle","NO_PROOF","no sandbox contract evidence"),("Withdrawal safety","BLOCKED","no provider/custody evidence"),("AI non-authority","NO_PROOF","no runtime/bypass test"),("Transaction guard","NO_PROOF","no decoder/simulation test"),("Reconciliation","NO_PROOF","no observed comparison run"),("Paper trading","NO_PROOF","no isolated replay"),("Testnet","BLOCKED","no scope-authorized environment"),("Chaos/security tests","NO_PROOF","no executed fixtures"),("Capital limits/kill switch","NO_PROOF","no implementation evidence"),("Manual mainnet approval","BLOCKED","no governed authorization")]
mat=["# Mainnet Readiness Matrix", "", "**Overall:** `MAINNET = BLOCKED`. PASS requires current independent evidence at exact scope; planning documents never qualify.", "", "| Requirement | Status | Reason / required gate |", "|---|---|---|"]
for a,b,c in readiness: mat.append(f"| {a} | {b} | {c} |")
write(".planning/master/MAINNET_READINESS_MATRIX.md", "\n".join(mat))

tech=["# Top 20 Technical Risks", ""]
fin=["# Top 20 Financial and Security Risks", ""]
tech_risks=["cross-module financial write","inbox/outbox replay ordering","schema drift","ledger rounding","state-machine gap","stale data","simulation drift","nonce conflict","chain reorg","partial fill","proxy upgrade","adapter outage","cache authority leak","audit rewrite","tenant RLS gap","secret leak","policy version race","environment mismatch","migration rollback","CI check spoofing"]
fin_risks=["forged webhook","duplicate credit","double withdrawal","address poisoning","wrong network","malicious calldata","key compromise","operator abuse","AI manipulation","MEV loss","liquidity collapse","stablecoin depeg","protocol exploit","exchange insolvency","bridge loss","sanctions/AML breach","legal classification","tax error","PII breach","reconciliation mismatch"]
for i,r in enumerate(tech_risks,1): tech.append(f"{i}. **{r}** — owner: Architecture/SRE; mitigation: explicit contract, fail-closed guard, negative test and incident runbook.")
for i,r in enumerate(fin_risks,1): fin.append(f"{i}. **{r}** — owner: Security/Risk/Compliance; mitigation: deterministic denial, limits/evidence/reconciliation and independent review.")
write(".planning/master/TOP_20_TECHNICAL_RISKS.md", "\n".join(tech))
write(".planning/master/TOP_20_FINANCIAL_SECURITY_RISKS.md", "\n".join(fin))

write(".planning/reviews/ADVERSARIAL_ARCHITECTURE_REVIEW.md", """# Adversarial Architecture Review

## Reviewer lenses
Security engineer: privileged-capability, secrets, signing and tenant substitution. Quant researcher: net-profit/latency/slippage/fill assumptions. Exchange engineer: capability, order lifecycle and reconciliation. Blockchain engineer: finality, reorg, nonce, calldata and proxy risk. Backend engineer: state/transaction/module ownership. SRE: outage, lag, recovery and observability. Financial auditor: journal/availability/evidence/correction. Fraud specialist: account takeover, withdrawal and payment abuse. Red team: malicious AI/provider/user input.

## Surviving findings
1. Local transactions are not external settlement; correlate independent evidence.
2. Ledger is financial availability authority; workflow/provider tables are not substitutes.
3. AI is input, not authority; all unknown actions deny.
4. Capability and mainnet authorization must be scoped, expiring, revocable and attested.
5. Hash-linked Postgres audit detects tampering only; stronger integrity needs external anchoring.
6. Venue/chain/LP failure domains stay separate.
7. Documentation/card count is not readiness proof.

## Required adversarial tests
Forged/replayed webhook; conflicting provider evidence; cross-tenant object/key substitution; stale/revoked grant; prompt injection; malformed schema; arbitrary calldata; wrong network; destination mutation; ambiguous broadcast; nonce conflict; stale quote; partial fill; chain reorg; provider/RPC/db/cache outage; audit-chain tamper; policy downgrade; environment attestation mismatch; mainnet feature-flag bypass.
""")

write("docs/testing/TESTING_STRATEGY.md", """# Testing Strategy

## Evidence levels
Planning integrity is not product proof. Future proof is tiered: unit → contract → property/model → integration sandbox → paper replay → testnet → controlled mainnet gate. A skip, no-test run, mock-only path or stale SHA is `NO_PROOF`.

## Non-vacuous suites
- Ledger: balance/conservation/idempotency/compensation property tests.
- State machines: generated legal/illegal/retry/expiry/revocation transitions.
- Contracts: producer/consumer schema compatibility, unknown version/action and envelope replay.
- Security: tenant substitution, capability attenuation, secret redaction, forged webhook, malicious proposal/calldata.
- Chaos: provider/RPC/database/cache outage, timeout, duplicate/reordered event, gas spike, reorg, partial fill.
- Architecture: forbidden dependency/write and privileged bypass tests.
- Release: exact-SHA CI, SBOM/provenance, migration replay, rollback and environment isolation.

Every future acceptance test uses `@spec:AC-...` and a PR/requirement trace reference. No future task is complete until the test runner and ONP audit are green.
""")

write("docs/architecture/README.md", "# Architecture Index\n\nSee SYSTEM_ARCHITECTURE, DOMAIN_MODEL, DATA_MODEL, CUSTODY_MODEL, TRUST_BOUNDARIES, THREAT_MODEL and `diagrams/` for the canonical planning design.\n")
write("docs/specifications/README.md", "# Specifications Index\n\nEach uppercase `*_SPEC.md` is normative planning input. Supporting formalization is under `docs/reference-formalization/`; it is not implementation evidence.\n")
write("docs/README.md", "# Crypto Automation Platform — Planning Baseline\n\nThis repository contains planning-only SDD artifacts. `MAINNET = BLOCKED`; no runtime, financial provider, wallet, trade or deployment capability is present.\n\n- `architecture/` — boundaries and diagrams\n- `specifications/` — component requirements\n- `security/` — trust and threats\n- `risk/` — risk policy documents\n- `compliance/` — legal/compliance gates\n- `adrs/` — decisions\n- `testing/` — future proof strategy\n- `reference-formalization/` — independent planner input, retained as reference\n")

# Integrity report (validates documentation topology only).
required = list(specs) + [f"docs/adrs/{x[0]}" for x in adrs] + [f"docs/architecture/diagrams/{x}" for x in diagrams] + [f".planning/contracts/{x}" for x in contracts] + [".planning/queue/PR_CARDS.md", ".planning/queue/queue.json", ".planning/queue/DEPENDENCY_DAG.mmd", ".planning/queue/QUEUE_INDEX.md", ".planning/master/TRACEABILITY_MATRIX.md", ".planning/master/MAINNET_READINESS_MATRIX.md", ".planning/master/TOP_20_TECHNICAL_RISKS.md", ".planning/master/TOP_20_FINANCIAL_SECURITY_RISKS.md", ".planning/reviews/ADVERSARIAL_ARCHITECTURE_REVIEW.md", "docs/testing/TESTING_STRATEGY.md"]
missing=[p for p in required if not (ROOT/p).exists()]
byid={c['id']:c for c in cards}
indeg={c['id']:0 for c in cards}; adj=defaultdict(list)
for a,b in edges:
    indeg[b]+=1; adj[a].append(b)
q=deque(k for k,v in indeg.items() if v==0); visited=[]
while q:
    x=q.popleft(); visited.append(x)
    for y in adj[x]:
        indeg[y]-=1
        if indeg[y]==0:q.append(y)
report={"status":"PASS" if not missing and len(visited)==len(cards) else "FAIL","required_files":len(required),"missing":missing,"adr_count":len(adrs),"diagram_count":len(diagrams),"contract_count":len(contracts),"queue_card_count":len(cards),"dag_acyclic":len(visited)==len(cards),"traceability_rows":len(topics),"mainnet":"BLOCKED","note":"PASS validates document topology only; it is not implementation, provider, legal, security, test, deployment or mainnet proof."}
write(".planning/master/PLANNING_INTEGRITY_REPORT.json", json.dumps(report, indent=2))
print(json.dumps(report, indent=2))
